spring.application.name=real-time-crypto-analytics-engine

# Enable Java 21 Virtual Threads natively in Spring Boot 3.2+
spring.threads.virtual.enabled=true

# Actuator & Prometheus
management.endpoints.web.exposure.include=prometheus
management.metrics.export.prometheus.enabled=true

# Redis Reactive Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# R2DBC H2 Configuration (PostgreSQL Mode)
spring.r2dbc.url=r2dbc:h2:mem:///testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.r2dbc.username=sa
spring.r2dbc.password=
spring.sql.init.mode=always

# Spring Boot server ko bolenge gracefully close hone ko
server.shutdown=graceful

# JVM shutdown hook ko 15 seconds ka time milega in-flight operations complete karne ke liye
spring.lifecycle.timeout-per-shutdown-phase=15s

# Server Port
server.port=8080
